apiVersion: v1
kind: Service
metadata:
  name: menuserviceservice
spec:
  type: NodePort
  selector:
    app: menuservice
  ports:
    - protocol: TCP
      nodePort: 30082
      port: 9744
      targetPort: 9744